version: "3"
services:

  proxy:
    build: ./proxy
    networks:
      - frontend
  app:
    build: ./app
    networks:
      - frontend
      - backend
  db:
    image: postgres
    networks:
      - backend

networks:
  frontend:

    driver: custom-dirver-1
  backend:

    driver: custom-driver-2
    driver:_opts:
      foo: "1"
      bar: "2"
